// Command genarith regenerates the verified field and scalar arithmetic used
// by the two short-Weierstrass curve backends.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

const image = "ghcr.io/islishude/fiat-crypto-go-tool@sha256:fa7d326be7c8ce419573e4f3165a88a41dfb0d29276887dd3c9de643f2723424"

type outputSpec struct {
	path       string
	entrypoint string
	args       []string
}

var check = flag.Bool("check", false, "compare generated output without writing files")

func main() {
	flag.Parse()
	root, err := repositoryRoot()
	if err != nil {
		fatal(err)
	}

	specs := []outputSpec{
		fiatSpec("internal/secp256k1/fiat_field.go", "secp256k1", "secp256k1field", "0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f", fieldOperations()),
		fiatSpec("internal/secp256k1/fiat_scalar.go", "secp256k1", "secp256k1scalar", "0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141", scalarOperations()),
		fiatSpec("internal/nistp256/fiat_field.go", "nistp256", "nistp256field", "0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff", fieldOperations()),
		fiatSpec("internal/nistp256/fiat_scalar.go", "nistp256", "nistp256scalar", "0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551", scalarOperations()),
		addchainSpec("internal/secp256k1/field_invert.go", "internal/gen/secp256k1_invert.tmpl", "internal/gen/secp256k1_invert.acc"),
		addchainSpec("internal/secp256k1/field_sqrt.go", "internal/gen/secp256k1_sqrt.tmpl", "internal/gen/secp256k1_sqrt.acc"),
		addchainSpec("internal/nistp256/field_invert.go", "internal/gen/nistp256_invert.tmpl", "internal/gen/nistp256_invert.acc"),
		addchainSpec("internal/nistp256/field_sqrt.go", "internal/gen/nistp256_sqrt.tmpl", "internal/gen/nistp256_sqrt.acc"),
	}

	failed := false
	for _, spec := range specs {
		generated, err := generate(root, spec)
		if err != nil {
			fatal(fmt.Errorf("generate %s: %w", spec.path, err))
		}
		path := filepath.Join(root, spec.path)
		if *check {
			current, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(current, generated) {
				fmt.Fprintf(os.Stderr, "%s is stale\n", spec.path)
				failed = true
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, generated, 0o644); err != nil {
			fatal(err)
		}
	}
	if failed {
		os.Exit(1)
	}
}

func repositoryRoot() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("resolve generator source path")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "../../..")), nil
}

func fiatSpec(path, pkg, description, modulus string, operations []string) outputSpec {
	args := []string{
		"word-by-word-montgomery",
		"--lang", "Go",
		"--package-name", pkg,
		"--no-wide-int",
		"--relax-primitive-carry-to-bitwidth", "32,64",
		"--internal-static",
		"--cmovznz-by-mul",
		"--doc-newline-in-typedef-bounds",
		"--doc-prepend-header", "Code generated by Fiat Cryptography. DO NOT EDIT.",
		"--doc-text-before-function-name", "",
		"--doc-text-before-type-name", "",
		description, "64", modulus,
	}
	args = append(args, operations...)
	return outputSpec{path: path, entrypoint: "fiat_crypto", args: args}
}

func fieldOperations() []string {
	return []string{"mul", "square", "add", "sub", "opp", "from_montgomery", "to_montgomery", "nonzero", "selectznz", "to_bytes", "from_bytes", "one", "msat"}
}

func scalarOperations() []string {
	return []string{"mul", "square", "add", "sub", "opp", "from_montgomery", "to_montgomery", "nonzero", "selectznz", "to_bytes", "from_bytes", "one", "msat"}
}

func addchainSpec(path, template, chain string) outputSpec {
	return outputSpec{
		path:       path,
		entrypoint: "addchain",
		args:       []string{"gen", "-tmpl", "/src/" + template, "/src/" + chain},
	}
}

func generate(root string, spec outputSpec) ([]byte, error) {
	args := []string{"run", "--rm", "--volume", root + ":/src:ro", "--entrypoint", spec.entrypoint, image}
	args = append(args, spec.args...)
	cmd := exec.Command("docker", args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("docker: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	if bytes.Contains(out, []byte("TODO")) {
		return nil, fmt.Errorf("generated output contains TODO marker")
	}
	formatted, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	return formatted, nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
