// Code generated by addchain. DO NOT EDIT.

package nistp256

// invert sets z = 1/x (mod p) and returns z.
func (z *fieldElement) invert(x *fieldElement) *fieldElement {
	var (
		t0 = new(fieldElement)
		t1 = new(fieldElement)
	)

	z.square(x)
	z.mul(x, z)
	z.square(z)
	z.mul(x, z)
	t0.square(z)
	for s := 1; s < 3; s++ {
		t0.square(t0)
	}
	t0.mul(z, t0)
	t1.square(t0)
	for s := 1; s < 6; s++ {
		t1.square(t1)
	}
	t0.mul(t0, t1)
	for s := 0; s < 3; s++ {
		t0.square(t0)
	}
	z.mul(z, t0)
	t0.square(z)
	t0.mul(x, t0)
	t1.square(t0)
	for s := 1; s < 16; s++ {
		t1.square(t1)
	}
	t0.mul(t0, t1)
	for s := 0; s < 15; s++ {
		t0.square(t0)
	}
	z.mul(z, t0)
	for s := 0; s < 17; s++ {
		t0.square(t0)
	}
	t0.mul(x, t0)
	for s := 0; s < 143; s++ {
		t0.square(t0)
	}
	t0.mul(z, t0)
	for s := 0; s < 47; s++ {
		t0.square(t0)
	}
	z.mul(z, t0)
	for s := 0; s < 2; s++ {
		z.square(z)
	}
	z.mul(x, z)
	return z
}
