// Code generated by addchain. DO NOT EDIT.

package nistp256

// sqrtCandidate sets z = x^((p+1)/4) (mod p) and returns z.
func (z *fieldElement) sqrtCandidate(x *fieldElement) *fieldElement {
	var (
		t0 = new(fieldElement)
	)

	z.square(x)
	z.mul(x, z)
	t0.square(z)
	for s := 1; s < 2; s++ {
		t0.square(t0)
	}
	z.mul(z, t0)
	t0.square(z)
	for s := 1; s < 4; s++ {
		t0.square(t0)
	}
	z.mul(z, t0)
	t0.square(z)
	for s := 1; s < 8; s++ {
		t0.square(t0)
	}
	z.mul(z, t0)
	t0.square(z)
	for s := 1; s < 16; s++ {
		t0.square(t0)
	}
	z.mul(z, t0)
	for s := 0; s < 32; s++ {
		z.square(z)
	}
	z.mul(x, z)
	for s := 0; s < 96; s++ {
		z.square(z)
	}
	z.mul(x, z)
	for s := 0; s < 94; s++ {
		z.square(z)
	}
	return z
}
