// Code generated by addchain. DO NOT EDIT.

package nistp256

// invert sets z = 1/x (mod p) and returns z.
func (z *fieldElement) invert(x *fieldElement) *fieldElement {
	var (
		t0 = new(fieldElement)
		t1 = new(fieldElement)
	)

	z.square(x)
	z.mul(x, z)
	z.square(z)
	z.mul(x, z)
	t0.square(z)
	for range 3 {
		t0.square(t0)
	}
	t0.mul(z, t0)
	t1.square(t0)
	for range 6 {
		t1.square(t1)
	}
	t0.mul(t0, t1)
	for range 3 {
		t0.square(t0)
	}
	z.mul(z, t0)
	t0.square(z)
	t0.mul(x, t0)
	t1.square(t0)
	for range 16 {
		t1.square(t1)
	}
	t0.mul(t0, t1)
	for range 15 {
		t0.square(t0)
	}
	z.mul(z, t0)
	for range 17 {
		t0.square(t0)
	}
	t0.mul(x, t0)
	for range 143 {
		t0.square(t0)
	}
	t0.mul(z, t0)
	for range 47 {
		t0.square(t0)
	}
	z.mul(z, t0)
	for range 2 {
		z.square(z)
	}
	z.mul(x, z)
	return z
}
