// Code generated by addchain. DO NOT EDIT.

package secp256k1

// invert sets z = 1/x (mod p) and returns z.
func (z *fieldElement) invert(x *fieldElement) *fieldElement {
	var (
		t0 = new(fieldElement)
		t1 = new(fieldElement)
		t2 = new(fieldElement)
		t3 = new(fieldElement)
		t4 = new(fieldElement)
	)

	t0.square(x)
	z.square(t0)
	z.mul(x, z)
	t1.mul(t0, z)
	t0.square(t1)
	t2.square(t0)
	for range 2 {
		t2.square(t2)
	}
	t2.mul(t1, t2)
	for range 4 {
		t2.square(t2)
	}
	t0.mul(t0, t2)
	t2.square(t0)
	for range 2 {
		t2.square(t2)
	}
	t2.mul(t1, t2)
	for range 10 {
		t2.square(t2)
	}
	t0.mul(t0, t2)
	t0.mul(x, t0)
	t3.square(t0)
	t2.square(t3)
	for range 2 {
		t2.square(t2)
	}
	t4.square(t2)
	for range 22 {
		t4.square(t4)
	}
	t2.mul(t2, t4)
	t4.square(t2)
	for range 20 {
		t4.square(t4)
	}
	t3.mul(t3, t4)
	for range 46 {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	t3.square(t2)
	for range 110 {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	t1.mul(t1, t2)
	for range 23 {
		t1.square(t1)
	}
	t0.mul(t0, t1)
	for range 7 {
		t0.square(t0)
	}
	t0.mul(z, t0)
	for range 3 {
		t0.square(t0)
	}
	z.mul(z, t0)
	return z
}
