// Code generated by addchain. DO NOT EDIT.

package secp256k1

// sqrtCandidate sets z = x^((p+1)/4) (mod p) and returns z.
func (z *fieldElement) sqrtCandidate(x *fieldElement) *fieldElement {
	var (
		t0 = new(fieldElement)
		t1 = new(fieldElement)
		t2 = new(fieldElement)
		t3 = new(fieldElement)
	)

	z.square(x)
	z.mul(x, z)
	t0.square(z)
	for s := 1; s < 2; s++ {
		t0.square(t0)
	}
	t0.mul(z, t0)
	t1.square(t0)
	t2.mul(x, t1)
	t1.square(t2)
	for s := 1; s < 2; s++ {
		t1.square(t1)
	}
	t1.mul(z, t1)
	t3.square(t1)
	for s := 1; s < 4; s++ {
		t3.square(t3)
	}
	t0.mul(t0, t3)
	t3.square(t0)
	for s := 1; s < 11; s++ {
		t3.square(t3)
	}
	t0.mul(t0, t3)
	t3.square(t0)
	for s := 1; s < 5; s++ {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	t3.square(t2)
	for s := 1; s < 27; s++ {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	t3.square(t2)
	for s := 1; s < 54; s++ {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	t3.square(t2)
	for s := 1; s < 108; s++ {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	for s := 0; s < 7; s++ {
		t2.square(t2)
	}
	t1.mul(t1, t2)
	for s := 0; s < 23; s++ {
		t1.square(t1)
	}
	t0.mul(t0, t1)
	for s := 0; s < 6; s++ {
		t0.square(t0)
	}
	z.mul(z, t0)
	for s := 0; s < 2; s++ {
		z.square(z)
	}
	return z
}
