// Code generated by addchain. DO NOT EDIT.

package secp256k1

// sqrtCandidate sets z = x^((p+1)/4) (mod p) and returns z.
func (z *fieldElement) sqrtCandidate(x *fieldElement) *fieldElement {
	var (
		t0 = new(fieldElement)
		t1 = new(fieldElement)
		t2 = new(fieldElement)
		t3 = new(fieldElement)
	)

	z.square(x)
	z.mul(x, z)
	t0.square(z)
	for range 2 {
		t0.square(t0)
	}
	t0.mul(z, t0)
	t1.square(t0)
	t2.mul(x, t1)
	t1.square(t2)
	for range 2 {
		t1.square(t1)
	}
	t1.mul(z, t1)
	t3.square(t1)
	for range 4 {
		t3.square(t3)
	}
	t0.mul(t0, t3)
	t3.square(t0)
	for range 11 {
		t3.square(t3)
	}
	t0.mul(t0, t3)
	t3.square(t0)
	for range 5 {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	t3.square(t2)
	for range 27 {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	t3.square(t2)
	for range 54 {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	t3.square(t2)
	for range 108 {
		t3.square(t3)
	}
	t2.mul(t2, t3)
	for range 7 {
		t2.square(t2)
	}
	t1.mul(t1, t2)
	for range 23 {
		t1.square(t1)
	}
	t0.mul(t0, t1)
	for range 6 {
		t0.square(t0)
	}
	z.mul(z, t0)
	for range 2 {
		z.square(z)
	}
	return z
}
