name: test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: ["^1.26", "^1.25"]
    steps:
      - uses: actions/checkout@v6

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: "${{ matrix.golang }}"
          check-latest: true

      - run: go build ./...
      - run: gofmt -d .
      - run: go vet ./...
      - run: go mod tidy -diff
      - run: go fix -diff ./...
      - run: go test -v ./...
